# Merge Script
if [ -d "scripts" ]; then
cd scripts/
fi

# 1
# Set bash script to exit immediately if any commands fail.
set -e
cd ../

# Setup some constants for use later on.
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

POSTFIX_SIMULATOR="_simulator"

echo -e "\n\n${GREEN}PREPARE BUILD ENVIRONMENT${NC}\n\n"

GENERATED_DIR_NAME="generated"

LOG_DIR="$GENERATED_DIR_NAME/log"
LOG_FILE_FRAMEWORK="$LOG_DIR/prebid_mobile_build.log"
LOG_FILE_FRAMEWORK_ABSOLUTE="$PWD/$LOG_FILE_FRAMEWORK"

XCODE_BUILD_DIR="$GENERATED_DIR_NAME/xcodebuild"

XCODE_ARCHIVE_DIR="$GENERATED_DIR_NAME/archive"
XCODE_ARCHIVE_DIR_ABSOLUTE="$PWD/$GENERATED_DIR_NAME/archive"

OUTPUT_DIR="$GENERATED_DIR_NAME/output"
OUTPUT_DIR_ABSOLUTE="$PWD/$OUTPUT_DIR"

# If remnants from a previous build exist, delete them.
if [ -d "$GENERATED_DIR_NAME" ]; then
	rm -rf "$GENERATED_DIR_NAME"
fi

mkdir -p "$LOG_DIR"
touch "$LOG_FILE_FRAMEWORK"

echo -e "\n\n${GREEN}INSTALL PODS${NC}\n\n"

export PATH="/Users/distiller/.gem/ruby/2.7.0/bin:$PATH"
gem install cocoapods
pod install --repo-update

echo -e "\n\n${GREEN}BUILD PREBID MOBILE${NC}\n\n"

# The actual scheme names are prefixed by "Lib-" to disambiguate them from the autogenerated schemes associated
# with our SPM libraries that can mess up this build process"
#
# All module names below carry the "Veon" prefix to match the Xcode target names (and the Swift
# module names the source actually imports) — except the core "PrebidMobile", left unprefixed by
# team decision. See scripts/rename_targets_to_veon.rb for the rename that made this the case.
#
# ORDER MATTERS: a module must be listed after the modules it depends on.
#   PrebidMobile
#   ├── VeonPrebidMobileGAMEventHandlers / VeonPrebidMobileAdMobAdapters / VeonPrebidMobileMAXAdapters
#   └── VeonPrebidRemoteConfig
#       └── VeonPrebidMultiAdLoader
#           ├── VeonPrebidMultiAdLoaderGAM
#           └── VeonPrebidMultiAdLoaderYandex
#
# HOW TO ADD A NEW MODULE:
#   1. add a framework target to EventHandlers/EventHandlers.xcodeproj, named with the Veon prefix,
#   2. add a shared scheme "Lib-<Module>" (EventHandlers/EventHandlers.xcodeproj/xcshareddata/xcschemes),
#   3. add "<Module>" to the array below (and to testPrebidMobileAdapters.sh if it has tests),
#   4. add the podspec / SPM target.
schemes=(
	"PrebidMobile"
	"VeonPrebidMobileGAMEventHandlers"
	"VeonPrebidMobileAdMobAdapters"
	"VeonPrebidMobileMAXAdapters"
	"VeonPrebidRemoteConfig"
	"VeonPrebidMultiAdLoader"
	"VeonPrebidMultiAdLoaderGAM"
	"VeonPrebidMultiAdLoaderYandex"
)

# Fail fast (with a readable message) if a "Lib-" scheme is missing from the workspace,
# instead of an obscure xcodebuild error halfway through the build.
echo -e "\n${GREEN} - Checking that all schemes exist${NC}"
AVAILABLE_SCHEMES="$(xcodebuild -list -workspace PrebidMobile.xcworkspace 2>/dev/null || true)"
missing_schemes=()
for scheme in "${schemes[@]}"
do
	if ! echo "$AVAILABLE_SCHEMES" | grep -Eq "^[[:space:]]+Lib-${scheme}[[:space:]]*$"; then
		missing_schemes+=("Lib-${scheme}")
	fi
done
if [ ${#missing_schemes[@]} -ne 0 ]; then
	echo -e "${RED}Missing shared schemes in PrebidMobile.xcworkspace: ${missing_schemes[*]}${NC}"
	echo -e "${RED}Add them to EventHandlers/EventHandlers.xcodeproj/xcshareddata/xcschemes or remove the modules from 'schemes'.${NC}"
	exit 1
fi

# Schemes whose transitive CocoaPods dependencies need BUILD_LIBRARY_FOR_DISTRIBUTION=NO
# on specific Pods targets (see the Podfile's post_install hook) to avoid an ABI mismatch
# against a prebuilt vendor .xcframework. A command-line `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`
# passed to xcodebuild has the HIGHEST precedence and silently overrides that per-target
# xcconfig override for every target in the build graph, including transitively-linked Pods
# targets — so for these schemes we omit the flag on the command line entirely and rely on
# BUILD_LIBRARY_FOR_DISTRIBUTION already being set to YES on the scheme's own target in
# EventHandlers.xcodeproj (verified separately), which is unaffected by the Podfile hook.
NO_CMDLINE_LIBRARY_EVOLUTION_SCHEMES=(
	"VeonPrebidMultiAdLoaderYandex"
)

scheme_needs_cmdline_library_evolution_flag() {
	local scheme="$1"
	for excluded in "${NO_CMDLINE_LIBRARY_EVOLUTION_SCHEMES[@]}"; do
		if [ "$scheme" == "$excluded" ]; then
			return 1
		fi
	done
	return 0
}

for(( n=0; n<${#schemes[@]}; n++ ))
do
	LIBRARY_EVOLUTION_FLAG=()
	if scheme_needs_cmdline_library_evolution_flag "${schemes[$n]}"; then
		LIBRARY_EVOLUTION_FLAG=(BUILD_LIBRARY_FOR_DISTRIBUTION=YES)
	else
		echo -e "${GREEN} - ${schemes[$n]}: omitting BUILD_LIBRARY_FOR_DISTRIBUTION from the command line (see Podfile post_install hook)${NC}"
	fi

	# Build the framework for device and for simulator 
	echo -e "\n${GREEN} - Archiving ${schemes[$n]} for device${NC}"

	xcodebuild archive \
	only_active_arch=NO \
	defines_module=YES \
	SKIP_INSTALL=NO \
	"${LIBRARY_EVOLUTION_FLAG[@]}" \
	-workspace PrebidMobile.xcworkspace \
	-scheme "Lib-${schemes[$n]}" \
	-configuration Release \
	-arch arm64 \
	-sdk "iphoneos" \
	-derivedDataPath $XCODE_BUILD_DIR \
	-archivePath "$XCODE_ARCHIVE_DIR/${schemes[$n]}.xcarchive" \
	> "$LOG_FILE_FRAMEWORK" 2>&1 || { echo -e "${RED}Error in build check log "$LOG_FILE_FRAMEWORK_ABSOLUTE"${NC}"; exit 1;}
 
    echo "Find Framework ${schemes[$n]} for device"
    find "$XCODE_ARCHIVE_DIR" -type d,f

	echo -e "\n${GREEN} - Archiving ${schemes[$n]} for simulator${NC}"

	xcodebuild archive \
	only_active_arch=NO \
	defines_module=YES \
	SKIP_INSTALL=NO \
	"${LIBRARY_EVOLUTION_FLAG[@]}" \
	-workspace PrebidMobile.xcworkspace \
	-scheme "Lib-${schemes[$n]}" \
	-configuration Release \
	-sdk "iphonesimulator" \
	-arch x86_64 \
	-arch arm64 \
	-derivedDataPath $XCODE_BUILD_DIR \
	-archivePath "$XCODE_ARCHIVE_DIR/${schemes[$n]}$POSTFIX_SIMULATOR.xcarchive" \
	> "$LOG_FILE_FRAMEWORK" 2>&1 || { echo -e "${RED}Error in build check log "$LOG_FILE_FRAMEWORK_ABSOLUTE"${NC}"; exit 1;}
 
    echo "Find Framework ${schemes[$n]} for simulator"
    find "$XCODE_ARCHIVE_DIR" -type d,f

	echo -e "${GREEN} - Creating ${schemes[$n]} XCFramework${NC}"
	# Create XCFramework
    
	# eval
	eval " 
	xcodebuild -create-xcframework \
	    -framework "$XCODE_ARCHIVE_DIR/${schemes[$n]}.xcarchive/Products/Library/Frameworks/${schemes[$n]}.framework" \
	    -debug-symbols "$XCODE_ARCHIVE_DIR_ABSOLUTE/${schemes[$n]}.xcarchive/dSYMs/${schemes[$n]}.framework.dSYM" \
	    -framework "$XCODE_ARCHIVE_DIR/${schemes[$n]}$POSTFIX_SIMULATOR.xcarchive/Products/Library/Frameworks/${schemes[$n]}.framework" \
	    -debug-symbols "$XCODE_ARCHIVE_DIR_ABSOLUTE/${schemes[$n]}$POSTFIX_SIMULATOR.xcarchive/dSYMs/${schemes[$n]}.framework.dSYM" \
	    -output "$OUTPUT_DIR/XC${schemes[$n]}.xcframework"
	"

done

echo -e "\n${GREEN}Done!${NC} \n"
echo -e "XCFrameworks are located: "$OUTPUT_DIR_ABSOLUTE" \n"
echo -e "Build logs path is: "$LOG_FILE_FRAMEWORK_ABSOLUTE" \n"